# Generated by Django 2.2 on 2019-04-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='shortlink',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
