# Generated by Django 2.2 on 2019-04-08 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0002_auto_20190408_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='shortlink',
            new_name='slug',
        ),
    ]
