# Generated by Django 3.1 on 2020-08-24 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0003_auto_20190408_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
